---
title: "brouillon_funct"
format: html
---

Ce fichier est la pour travailler sur les fonctions et sur les visus avant de les mettre sur l'app

Il suffit d'ouvrir un chunk par fonction
```{r}

v <- crea_data("vmax", month_t = F) |> 
  rename("vitesse max" = y)
r <- crea_data("rmax", month_t = F) |> 
  rename("rayon max" = y)
p <- crea_data("pressure", month_t = F) |> 
  rename("pression" = y)

dt_cor <- v |> 
  left_join(r) |> 
  left_join(p) |> 
  select(- year)

library(corrplot)
library(GGally)

M<-cor(dt_cor)
head(round(M,2))
corrplot <- corrplot(M, type="upper")
corrplot(M, method="color", type="upper")

table(dt_cor)
plot(dt_cor)
ggpairs(dt_cor)

```

Si besoin, c'est possible de faire un fichier par personne



```{r}

dt_py <- dtp %>% group_by(year) %>% summarise (pland=mean(land=="TRUE")*100)


dt_py %>% ggplot(aes(x=as.numeric(year), y=pland))+
  geom_col(fill="steelblue",alpha=0.5) +
  geom_smooth(method = "lm") +
  scale_x_continuous(breaks=seq(min(dt_py$year),max(dt_py$year),by=5)) +
  labs(x="Années", y="Pourcentage de cyclones ayant touchés la terre")  +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(), #Suppression de la grille majeure
        panel.grid.minor = element_blank(), #suppression de la grille mineure
        panel.border = element_blank(), #suppression du cadre
        panel.background = element_blank(), #suppression du fond
        text = element_text(size = 18))

```

